---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["MACHINE_USER"] %>
  password: <%= ENV["MACHINE_PASS"] %>

provisioner:
  name: shell
  script: provision.ps1

platforms:
  - name: windows-2012R2

verifier:
  name: pester
  environment:
    API_KEY: Some key value
    PUSH_REPO: https://push.example.com
  downloads:
    "PesterTestResults.xml": "testresults/%{instance_name}/"

suites:
  - name: default
