---
driver:
  name: vagrant

provisioner:
  name: shell
  script: provision.ps1

platforms:
  - name: windows-2016
    driver_config:
      box: stefanscherer/windows_2016

verifier:
  name: pester
  remove_builtin_pester: false
  remove_builtin_powershellget: false
  environment:
    API_KEY: Some key value
    PUSH_REPO: https://push.example.com
  downloads:
    "PesterTestResults.xml": "testresults/%{instance_name}/"

suites:
  - name: default
